-- Hidden India database schema for Supabase
-- Firebase handles authentication. This table stores application profile data.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  firebase_uid text not null unique,
  name text not null,
  email text not null unique,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;

-- The Railway backend uses the Supabase secret key, so it can perform the
-- server-side upsert without exposing database credentials to the browser.
-- Do not put the secret key in the Vercel frontend.
